version: 2

sources: 
    - name: staging
      database: dtc-de-course-339115
      schema: trips_data_all
      tables:
        - name: yellow_tripdata
        - name: green_tripdata
        - name: fhv_tripdata
